AllCops:
  Exclude:
    - Rakefile
    - Berksfile
    - metadata.rb
    - vendor/**/*
Documentation:
  Enabled: false
Encoding:
  Enabled: false
Style/FileName:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
PerceivedComplexity:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
